Lab09: main.o
	g++ main.o -std=c++11 -g -Wall -o Lab09
main.o: executive.h executive.hpp binarynode.h binarynode.hpp bst.h bst.hpp HeapInterface.h min_k_heap.h max_k_heap.h min_k_heap.hpp max_k_heap.hpp main.cpp
	g++ -std=c++11 -g -Wall -c main.cpp

clean:
	rm *.o Lab09
