Lab7: main.o
	g++ main.o -std=c++11 -g -Wall -o Lab7
main.o: bubbleSort.cpp insertionSort.cpp quickSort.cpp mergeSort.cpp selectionSort.cpp main.cpp
	g++ -std=c++11 -g -Wall -c main.cpp
clean:
	rm *.o Lab7