build:
	g++ -std=c++14 -I"/usr/local/lib/restbed/distribution/include" main.cpp -L"/usr/local/lib/restbed/distribution/library" -lrestbed libs/json.cpp libs/mathLib.cpp -o prog
run:
	LD_LIBRARY_PATH=/usr/local/lib/restbed/distribution/library ./prog
